spring:
    profiles:
        active: test
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    batch:
        job:
            enabled: false

elasticsearch:
    hosts: http://localhost:9200